name: GitHub Pages Deployment

on:
  push:
    branches:
      - master  # master 브랜치에서 푸시되었을 때 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # build 폴더가 생성되도록 설정

      - name: Move build files to docs folder
        run: |
          mkdir -p ./docs
          cp -r ./build/* ./docs/  # build 파일을 docs 폴더로 복사

      - name: Commit and push to gh-pages
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Deploy GitHub Pages to docs folder"
          git push origin gh-pages  # gh-pages 브랜치로 푸시
